In [30]:
import pandas as pd
import seaborn as sns

df = pd.read_csv('dados/bmw.csv')
df.head()

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,5 Series,2014,11200,Automatic,67068,Diesel,125,57.6,2.0
1,6 Series,2018,27000,Automatic,14827,Petrol,145,42.8,2.0
2,5 Series,2016,16000,Automatic,62794,Diesel,160,51.4,3.0
3,1 Series,2017,12750,Automatic,26676,Diesel,145,72.4,1.5
4,7 Series,2014,14500,Automatic,39554,Diesel,160,50.4,3.0

In [28]:
df.groupby(['model', 'transmission']).price.describe().sort_values('mean', ascending=False)

                         count          mean           std      min       25%  \
model     transmission
 X7       Semi-Auto       38.0  70446.210526   5205.198836  61875.0  65287.50
          Automatic       17.0  68493.882353   4731.065616  59988.0  65520.00
 8 Series Semi-Auto       31.0  64043.387097   8910.734117  51980.0  58970.00
          Automatic        8.0  63821.125000   5855.505283  55980.0  59747.50
 M5       Semi-Auto       16.0  58582.750000  19359.353951  24310.0  53366.75
 i8       Automatic       17.0  57012.588235  11135.665321  37995.0  48898.00
 M5       Automatic       13.0  56747.384615  20199.564614  23490.0  35995.00
 X5       Semi-Auto      166.0  51116.174699   5079.358008  41211.0  47485.00
 M4       Automatic       30.0  47054.233333  14072.146700  26499.0  39962.50
 M2       Manual           1.0  46000.000000           NaN  46000.0  46000.00
 X6       Semi-Auto       76.0  45710.342105  14936.223387  15380.0  32598.75
 M2       Automatic        7.0  43039.142857   9031.452918  23495.0  42795.00
          Semi-Auto       13.0  42974.846154   4745.352601  31000.0  40995.00
 M4       Semi-Auto       90.0  42545.588889   9488.071684  28500.0  34960.25
 7 Series Semi-Auto       66.0  41477.984848  10978.946638  14798.0  33170.50
 X6       Automatic       30.0  39096.900000  17787.162221  13440.0  22318.50
 M3       Semi-Auto       14.0  37515.714286   8736.824493  25945.0  33150.00
 X4       Semi-Auto       98.0  36012.142857   8095.073415  18860.0  33995.75
 M4       Manual           5.0  33709.800000   4986.785307  27590.0  29197.00
 X5       Automatic      302.0  33349.254967  12032.513099   7250.0  24620.00
 M6       Semi-Auto        5.0  33306.000000  12664.131514  12495.0  34147.00
 Z4       Semi-Auto       65.0  31481.046154   6675.937552  13498.0  29990.00
 X3       Semi-Auto      305.0  31047.426230  10072.564139   5299.0  21990.00
 M6       Automatic        3.0  30330.000000   2757.118061  28490.0  28745.00
 M3       Automatic        4.0  29598.500000  17395.313708  14950.0  18511.75
 X4       Automatic       75.0  29552.746667  10372.967042  15199.0  21000.00
 7 Series Automatic       40.0  29437.275000  16489.179485   4995.0  13986.75
 X2       Semi-Auto      174.0  28882.051724   4206.538063  21726.0  25971.75
          Automatic       88.0  28727.068182   3774.250452  19999.0  26972.00
 Z4       Automatic       23.0  28204.869565  10570.370482   3495.0  23724.00
 6 Series Semi-Auto       50.0  27749.040000   7748.001586   9495.0  22574.50
 5 Series Semi-Auto      519.0  26306.119461   7220.439453   9998.0  21878.50
 X2       Manual          26.0  25026.923077   2832.236783  19240.0  23292.50
 4 Series Semi-Auto      497.0  24574.839034   5696.679813  11870.0  20498.00
 X3       Automatic      231.0  24354.805195  11044.147777   3495.0  16250.00
 3 Series Semi-Auto     1075.0  23900.199070   7322.811188   5695.0  18492.50
 X1       Semi-Auto      349.0  22252.816619   5197.216369   9527.0  18991.00
 2 Series Semi-Auto      514.0  21832.570039   6485.693290  10998.0  17995.75
 4 Series Automatic      376.0  21452.579787   6433.994887  10195.0  16495.00
 6 Series Automatic       58.0  21427.931034   8251.729656   4995.0  17049.75
 1 Series Semi-Auto      505.0  20355.057426   5598.903610   9444.0  15998.00
 5 Series Automatic      501.0  19490.423154   8481.142718   1595.0  12990.00
 X1       Automatic      227.0  19368.599119   5264.066230   6495.0  16555.50
 2 Series Automatic      303.0  19274.306931   5076.883171   8995.0  15083.50
 M3       Manual           9.0  19176.666667   7432.682742  10999.0  16950.00
 3 Series Automatic      830.0  18686.009639   8097.494388   1200.0  13491.25
 i3       Automatic       43.0  18667.116279   2663.548172  12500.0  16750.00
 X4       Manual           6.0  18578.833333   1314.856557  16700.0  17646.75
 4 Series Manual         122.0  17262.795082   5156.514605   8500.0  13999.00
 2 Series Manual         412.0  16873.378641   5026.203138   5895.0  12584.25
 1 Series Automatic      361.0  16777.692521   5639.712750   3500.0  12999.00
 X1       Manual         228.0  16533.390351   5801.726066   5994.0  13298.00
 Z3       Automatic        1.0  14995.000000           NaN  14995.0  14995.00
 3 Series Manual         538.0  13693.000000   6250.287928   1445.0   9940.50
 1 Series Manual        1103.0  13433.198549   4820.031480   1500.0  10225.00
 X3       Manual          15.0  13293.600000   5351.027455   3499.0  10274.50
 Z4       Manual          20.0  11061.450000   4214.030118   1995.0   9477.50
 5 Series Manual          36.0  10609.611111   2874.919808   1699.0   9300.00
 Z3       Manual           6.0   4298.333333    809.448372   3950.0   3950.00

                            50%       75%       max
model     transmission
 X7       Semi-Auto     69995.0  74102.50   79566.0
          Automatic     67986.0  69940.00   78386.0
 8 Series Semi-Auto     61485.0  67444.50   88980.0
          Automatic     63400.5  66224.50   73900.0
 M5       Semi-Auto     62939.0  70763.25   89900.0
 i8       Automatic     57870.0  64980.00   74226.0
 M5       Automatic     68850.0  69995.00   74988.0
 X5       Semi-Auto     49996.5  52990.00   72990.0
 M4       Automatic     45743.5  49871.25   99950.0
 M2       Manual        46000.0  46000.00   46000.0
 X6       Semi-Auto     42970.0  58607.50   69995.0
 M2       Automatic     46995.0  47597.50   49999.0
          Semi-Auto     44500.0  45980.00   48898.0
 M4       Semi-Auto     42742.5  48000.00   89990.0
 7 Series Semi-Auto     45649.0  49990.00   59995.0
 X6       Automatic     35495.0  56822.50   66290.0
 M3       Semi-Auto     37283.5  37992.50   62995.0
 X4       Semi-Auto     36490.0  41677.75   60995.0
 M4       Manual        35995.0  36991.00   38776.0
 X5       Automatic     30995.0  43946.00   73000.0
 M6       Semi-Auto     35898.0  36995.00   46995.0
 Z4       Semi-Auto     32450.0  34980.00   50800.0
 X3       Semi-Auto     32302.0  35995.00   69991.0
 M6       Automatic     29000.0  31250.00   33500.0
 M3       Automatic     24724.5  35811.25   53995.0
 X4       Automatic     23995.0  39992.50   55000.0
 7 Series Automatic     26474.5  47912.50   57000.0
 X2       Semi-Auto     28485.0  31587.50   44980.0
          Automatic     28000.0  30289.75   38350.0
 Z4       Automatic     31488.0  32982.50   43995.0
 6 Series Semi-Auto     27348.5  33313.75   44991.0
 5 Series Semi-Auto     26800.0  30980.00   54845.0
 X2       Manual        24985.0  26865.00   30990.0
 4 Series Semi-Auto     24490.0  27500.00   48155.0
 X3       Automatic     20850.0  32613.00   57680.0
 3 Series Semi-Auto     23285.0  28380.50   71990.0
 X1       Semi-Auto     20995.0  25999.00   37320.0
 2 Series Semi-Auto     21595.0  23998.75  123456.0
 4 Series Automatic     19762.5  25784.00   41990.0
 6 Series Automatic     20250.0  24311.75   52500.0
 1 Series Semi-Auto     19840.0  23052.00   38555.0
 5 Series Automatic     15999.0  26566.00   42995.0
 X1       Automatic     18727.0  22550.00   32995.0
 2 Series Automatic     19495.0  22283.00   37989.0
 M3       Manual        17650.0  17850.00   37991.0
 3 Series Automatic     16899.0  21375.00   53988.0
 i3       Automatic     19300.0  19999.00   23751.0
 X4       Manual        18937.5  19496.25   19999.0
 4 Series Manual        15974.0  18959.75   32995.0
 2 Series Manual        16085.5  20980.00   34950.0
 1 Series Automatic     15500.0  19750.00   34999.0
 X1       Manual        15450.5  18845.75   33400.0
 Z3       Automatic     14995.0  14995.00   14995.0
 3 Series Manual        12490.0  15500.00   36995.0
 1 Series Manual        12299.0  15919.50   27995.0
 X3       Manual        13999.0  16846.00   20800.0
 Z4       Manual        12240.0  13623.50   17990.0
 5 Series Manual        10870.0  12367.50   17500.0
 Z3       Manual         3972.5   3995.00    5950.0

In [3]:
import plotly.graph_objects as go
fig = go.Figure(data=go.Bar(y=[2, 3, 1]))
fig.write_html('first_figure.html', auto_open=True)

In [13]:
import plotly.express as px
import pandas as pd
# df = px.data.gapminder().query("year == 2007")
df = pd.read_csv('https://raw.githubusercontent.com/ronaldolagepessoa/data_science/master/dados/housing_ok.csv')
fig = px.density_mapbox(df, lat='latitude', lon='longitude', z='preco', radius=10,
                        center=dict(lat=0, lon=180), zoom=0,
                        mapbox_style="stamen-terrain")
fig.write_html('first_figure.html', auto_open=True)